version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smartshop-postgres
    environment:
      POSTGRES_USER: abdelouafi
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartshop
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: smartshop-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: abdelouafi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  pgdata:
